language: java
before_install:
  - mysql -e 'CREATE DATABASE contact;'
services:
  - mysql
sudo: false
install: mvn test
cache:
  directories:
  - $HOME/.m2
  script:
  mvn verify -B
script:
- ./mvnw clean install -B
